openapi: 3.0.0
info: 
  title: PointRend:image segmentation as rendering by ainize
  version: 0.1.1

servers: 
  - url: http://35.200.119.252:80


paths:
  /:
    post:
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image1:
                  type: string
                  format: binary
                image2:
                  type: string
                  format: binary

      responses:
        '200':
          description: OK
          content:
            image/*:
              schema:
                type: string
                format: binary
        '400':
          description: Bad request. User ID must be an integer and larger than 0.
        '401':
          description: Authorization information is missing or invalid.
        '404':
          description: A user with the specified ID was not found.
        '5XX':
          description: Unexpected error.
